version: '3'
networks:
  deqlms:
    driver: bridge
services:
  msprisma:
    image: prismagraphql/prisma:1.8
    container_name: msprisma
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: mspostgis
            port: 5432
            user: mspostgis
            password: mspostgis
            migrations: true
    networks:
      - deqlms
  mspostgis:
    image: "mdillon/postgis"
    container_name: mspostgis
    restart: always
    environment:
      POSTGRES_USER: mspostgis
      POSTGRES_PASSWORD: mspostgis
      POSTGRES_DB: prisma
    ports:
     - "5445:5432"
    networks:
      - deqlms
  mspgadmin:
    image: "dpage/pgadmin4"
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
     - "6543:80"
    networks:
      - deqlms
  msredis:
    image: "redis"
    container_name: msredis
    restart: always
    ports:
     - "32768:6379"
    networks:
      - deqlms
